# Generated by Django 5.1.15 on 2026-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_weeklyleaderboardsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('compliance_decision', 'Compliance Decision'), ('prompt_selection', 'Prompt Selection'), ('prompt_ranking', 'Prompt Ranking'), ('compliance_traffic_light', 'Compliance Traffic Light')], max_length=32),
        ),
    ]
