# Generated by Django 5.1.15 on 2026-06-18 10:10

from django.db import migrations, models


# Legacy default titles that are now represented by an empty title and
# localized for display in the frontend.
LEGACY_DEFAULT_TITLES = ('Neuer Chat', 'New chat')


def clear_legacy_default_titles(apps, schema_editor):
    AgentChat = apps.get_model('accounts', 'AgentChat')
    AgentChat.objects.filter(title__in=LEGACY_DEFAULT_TITLES).update(title='')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_dailymissionreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentchat',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(clear_legacy_default_titles, migrations.RunPython.noop),
    ]
