# Generated by Django 5.1.15 on 2026-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_agentchat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_role',
            field=models.CharField(choices=[('all', 'All Roles'), ('accountant', 'Accountant'), ('controller', 'Controller')], default='all', max_length=32),
        ),
    ]
